### ISSUE TITLE
Issue with the help command

### ISSUE THREAD

**Issue by sudojunior** [Sven65/Sledgehammer#6]
```js
Unhandled rejection TypeError: Cannot read property 'indexOf' of undefined
    at Sledgehammer.Commands.All.map (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\Sledgehammer\Commands\General\Help.js:50:36)
    at Array.map (native)
    at Execute.s.prefix.then (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\Sledgehammer\Commands\General\Help.js:41:43)
    at tryCatcher (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Morgan\Desktop\Bot Code for Discord\Sledgehammer\node_modules\rethinkdb\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by sudojunior** [comment]
Fixed Help Command
Changes can be seen in the rewrite branch or https://github.com/Sven65/Sledgehammer/commit/d846cee8ae2f0e51cede5c1c9e85c640f9db891e
